# .travis.yml file
language: node_js
node_js:
  - '14'
  - '16'
services: mongodb
cache:
  directories:
    - 'node_modules'
install:
  - npm install
deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
      branch: master
