# .travis.yml file
language: node_js
node_js:
  - '16'
services: mongodb
install:
  - npm install
deploy:
  - provider: script
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
      branch: main
